name: Cypress Test Run

# Triggers
on:
  push:
    branches: [ main ]  # Runs on push to main
  pull_request:
    branches: [ main ]  # Runs on PR to main
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Change this to match your version

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
